### ISSUE TITLE
./configure: syntax error near unexpected token `POPT,'

### ISSUE THREAD

**Issue by Nick135** [rdoeffinger/iec16022#14]
I get a syntax Error when I run "./configure" on Debian 9 32Bit

````
./configure: line 11955: syntax error near unexpected token `POPT,'
./configure: line 11955: `PKG_CHECK_MODULES(POPT, popt, ,'
````

**Comment by dende** [comment]
i get this too on Kali 64Bit

**Comment by rdoeffinger** [comment]
You ran ./autogen.sh ?  That should call ./configure, so it should not be necessary to run it explicitly. The autogen.sh is also the step that you should watch for errors because that's where something goes wrong.
Do you have pkg-config installed?

**Comment by rdoeffinger** [comment]
Reading elsewhere, e.g. https://github.com/ntop/ntopng/issues/2748 suggests it should indeed be the missing pkg-config.
I've not seen an explanation why autoconf doesn't handle a missing dependency in a more sensible manner though, failing in this way seems rather ridiculous.

**Comment by rdoeffinger** [comment]
Added workaround so it also works without pkg-config.

**Comment by dende** [comment]
can confirm it works now! Thanks for the effort!

Am Sa., 19. März 2022 um 17:27 Uhr schrieb Reimar Döffinger <
***@***.***>:
