### ISSUE TITLE
Incorrect results

### ISSUE THREAD

**Issue by webloft** [rdoeffinger/iec16022#15]
Some string or length produces incorrect results, eg. the substring ":62" gets then encoded as ":{62" near the end of data or data is truncated. Complete string is 63 chars long.

Cannot post the strings here because it may expose sensitive data.
If someone responses to this I will try to find a random test string.
Forcing the size can prevent the bug.

**Comment by rdoeffinger** [comment]
An example string would indeed be massively helpful!

**Comment by webloft** [comment]
I'm afraid I cannot produce a truncated result but I can you give this string which gets encoded like explained above:

`10000000000&AA0000&000000000000&#FFFFFFFFFFFF&00:00:00:A3:C5:62`

**Comment by rdoeffinger** [comment]
Should be fixed. Not sure it explains/will fix the truncation issue you saw though...

**Comment by webloft** [comment]
Looks good. Thank you!

Well, I just saw this truncate issue by testing random data, so I don't remember exactly. However, if I stumble over it again, I will open a new ticket.
