### ISSUE TITLE
Missing tag for release 0.3.1

### ISSUE THREAD

**Issue by remvee** [rdoeffinger/iec16022#16]
`git tag v0.3.1 c9a9fd926fd1e6cca9782fe3f8c2bab66010ca51`

**Comment by remvee** [comment]
Fixed commit in description acc064132a7656d337c90f36541f7e81998a978b -> c9a9fd926fd1e6cca9782fe3f8c2bab66010ca51 because latter does not build.

**Comment by rdoeffinger** [comment]
I actually never released 0.3.1 because I did not have a working build setup.
I'll do it now, even though it's going to be a bit messy due to the NEWS entry being ancient.
