### ISSUE TITLE
Update package meta data

### ISSUE THREAD

**Issue by mhei** [rdoeffinger/iec16022#3]
- the package release tarball 0.2.6 contains still the version 0.2.5 in configure.ac
- maintainers e-mail address should be updated
- man page also contains version tag 0.2.5
- Changelog could be updated

Sorry to not create a PR, but I'm limited in time at the moment.

**Comment by rdoeffinger** [comment]
Thanks for pointing it out. I won't update that release (I don't like moving tags around and it's not that critical), but I have writing a proper release script on my TODO.
Trying to remember what things to manually change just doesn't really work.
